---
- name: Playbook to install Redis
  hosts: all
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    redis_version: "6.2.5"  # Specify the desired Redis version here
  roles:
    - redis
